### ISSUE TITLE
Support for environment variables defined in serverless.yml

### ISSUE THREAD

**Issue by elkelk** [rametta/coppa#3]
When a function has defined environment variables in the serverless.yml they don't seem to be available at run time.

**Comment by rametta** [comment]
Hi @elkelk , I'm not sure what you mean. The env vars are not available where exactly? Can you provide some examples?

**Comment by elkelk** [comment]
Yeah, sorry for the lack of details. I have this function config in my serverless.yml:
```
...
functions:
  reviews:
    handler: aHandler
    environment:
      SOME_APP_KEY: ${file(./config/secrets.json):some_app_key}
      SOME_SECRET_KEY: ${file(./config/secrets.json):some_secret_key}
    events:
      - http: reviews
...
```
The variables `SOME_APP_KEY` and `SOME_SECRET_KEY` don't seem to be available in process.env, although they are when I deploy to google cloud functions.
